# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wallet.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\016org.jura.protoB\013WalletProto'),
  serialized_pb=_b('\n\x0cwallet.proto\x12\x05proto\x1a\x0c\x63ommon.proto\"D\n\x16MakeTransactionRequest\x12*\n\x0btransaction\x18\x01 \x01(\x0b\x32\x15.proto.RawTransaction\"*\n\x17MakeTransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x13\x43heckBalanceRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\"\'\n\x14\x43heckBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x04\"/\n\x1cGetTransactionHistoryRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0c\"Q\n\x1dGetTransactionHistoryResponse\x12\x30\n\x10transaction_list\x18\x01 \x01(\x0b\x32\x16.proto.TransactionList2\x94\x02\n\rWalletService\x12R\n\x0fMakeTransaction\x12\x1d.proto.MakeTransactionRequest\x1a\x1e.proto.MakeTransactionResponse\"\x00\x12I\n\x0c\x43heckBalance\x12\x1a.proto.CheckBalanceRequest\x1a\x1b.proto.CheckBalanceResponse\"\x00\x12\x64\n\x15GetTransactionHistory\x12#.proto.GetTransactionHistoryRequest\x1a$.proto.GetTransactionHistoryResponse\"\x00\x42\x1d\n\x0eorg.jura.protoB\x0bWalletProtob\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_MAKETRANSACTIONREQUEST = _descriptor.Descriptor(
  name='MakeTransactionRequest',
  full_name='proto.MakeTransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='proto.MakeTransactionRequest.transaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=105,
)


_MAKETRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='MakeTransactionResponse',
  full_name='proto.MakeTransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.MakeTransactionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=149,
)


_CHECKBALANCEREQUEST = _descriptor.Descriptor(
  name='CheckBalanceRequest',
  full_name='proto.CheckBalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='proto.CheckBalanceRequest.account', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=189,
)


_CHECKBALANCERESPONSE = _descriptor.Descriptor(
  name='CheckBalanceResponse',
  full_name='proto.CheckBalanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='proto.CheckBalanceResponse.balance', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=230,
)


_GETTRANSACTIONHISTORYREQUEST = _descriptor.Descriptor(
  name='GetTransactionHistoryRequest',
  full_name='proto.GetTransactionHistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='proto.GetTransactionHistoryRequest.account', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=279,
)


_GETTRANSACTIONHISTORYRESPONSE = _descriptor.Descriptor(
  name='GetTransactionHistoryResponse',
  full_name='proto.GetTransactionHistoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_list', full_name='proto.GetTransactionHistoryResponse.transaction_list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=362,
)

_MAKETRANSACTIONREQUEST.fields_by_name['transaction'].message_type = common__pb2._RAWTRANSACTION
_GETTRANSACTIONHISTORYRESPONSE.fields_by_name['transaction_list'].message_type = common__pb2._TRANSACTIONLIST
DESCRIPTOR.message_types_by_name['MakeTransactionRequest'] = _MAKETRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['MakeTransactionResponse'] = _MAKETRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['CheckBalanceRequest'] = _CHECKBALANCEREQUEST
DESCRIPTOR.message_types_by_name['CheckBalanceResponse'] = _CHECKBALANCERESPONSE
DESCRIPTOR.message_types_by_name['GetTransactionHistoryRequest'] = _GETTRANSACTIONHISTORYREQUEST
DESCRIPTOR.message_types_by_name['GetTransactionHistoryResponse'] = _GETTRANSACTIONHISTORYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MakeTransactionRequest = _reflection.GeneratedProtocolMessageType('MakeTransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAKETRANSACTIONREQUEST,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.MakeTransactionRequest)
  })
_sym_db.RegisterMessage(MakeTransactionRequest)

MakeTransactionResponse = _reflection.GeneratedProtocolMessageType('MakeTransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAKETRANSACTIONRESPONSE,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.MakeTransactionResponse)
  })
_sym_db.RegisterMessage(MakeTransactionResponse)

CheckBalanceRequest = _reflection.GeneratedProtocolMessageType('CheckBalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKBALANCEREQUEST,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.CheckBalanceRequest)
  })
_sym_db.RegisterMessage(CheckBalanceRequest)

CheckBalanceResponse = _reflection.GeneratedProtocolMessageType('CheckBalanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKBALANCERESPONSE,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.CheckBalanceResponse)
  })
_sym_db.RegisterMessage(CheckBalanceResponse)

GetTransactionHistoryRequest = _reflection.GeneratedProtocolMessageType('GetTransactionHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONHISTORYREQUEST,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetTransactionHistoryRequest)
  })
_sym_db.RegisterMessage(GetTransactionHistoryRequest)

GetTransactionHistoryResponse = _reflection.GeneratedProtocolMessageType('GetTransactionHistoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONHISTORYRESPONSE,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetTransactionHistoryResponse)
  })
_sym_db.RegisterMessage(GetTransactionHistoryResponse)


DESCRIPTOR._options = None

_WALLETSERVICE = _descriptor.ServiceDescriptor(
  name='WalletService',
  full_name='proto.WalletService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=365,
  serialized_end=641,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeTransaction',
    full_name='proto.WalletService.MakeTransaction',
    index=0,
    containing_service=None,
    input_type=_MAKETRANSACTIONREQUEST,
    output_type=_MAKETRANSACTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckBalance',
    full_name='proto.WalletService.CheckBalance',
    index=1,
    containing_service=None,
    input_type=_CHECKBALANCEREQUEST,
    output_type=_CHECKBALANCERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTransactionHistory',
    full_name='proto.WalletService.GetTransactionHistory',
    index=2,
    containing_service=None,
    input_type=_GETTRANSACTIONHISTORYREQUEST,
    output_type=_GETTRANSACTIONHISTORYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WALLETSERVICE)

DESCRIPTOR.services_by_name['WalletService'] = _WALLETSERVICE

# @@protoc_insertion_point(module_scope)
